import fs from 'node:fs'
import path from 'node:path'

type ClientGraphSubType =
  | 'character_skill'
  | 'creation_skill'
  | 'creation_status'
  | 'creation_status_decision'
  | 'bool_filter'
  | 'int_filter'

type ClientGraphCapability = Record<
  ClientGraphSubType,
  {
    beyond: { status: string; reason: string }
    classic: { status: string; reason: string }
  }
>

const SUB_TYPES: readonly ClientGraphSubType[] = [
  'character_skill',
  'creation_skill',
  'creation_status',
  'creation_status_decision',
  'bool_filter',
  'int_filter'
]

const GRAPH_ENCODING_BY_SUB_TYPE: Record<
  ClientGraphSubType,
  { graphType: number; graphWhich: number }
> = {
  bool_filter: { graphType: 20001, graphWhich: 10 },
  int_filter: { graphType: 20006, graphWhich: 47 },
  character_skill: { graphType: 20002, graphWhich: 11 },
  creation_skill: { graphType: 20008, graphWhich: 52 },
  creation_status_decision: { graphType: 20007, graphWhich: 51 },
  creation_status: { graphType: 20009, graphWhich: 53 }
}

function readJson<T>(file: string): T {
  return JSON.parse(fs.readFileSync(file, 'utf8')) as T
}

function write(file: string, body: string) {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, body.endsWith('\n') ? body : `${body}\n`, 'utf8')
}

function assertCompleteCapability(capability: Partial<ClientGraphCapability>) {
  const missing = SUB_TYPES.filter((subType) => !capability[subType])
  if (missing.length) {
    throw new Error(`client graph capability missing sub types: ${missing.join(', ')}`)
  }
}

function generatedHeader() {
  return '// This file is generated by scripts/client-nodegraph/generate-client-nodegraph-modules.ts.\n'
}

function jsonConst(value: unknown) {
  return JSON.stringify(value, null, 2)
}

function emitClientGraphEncoding() {
  write(
    'src/thirdparty/Genshin-Impact-Miliastra-Wonderland-Code-Node-Editor-Pack/node_data/client_graph_encoding.ts',
    `${generatedHeader()}import type { ClientGraphSubType } from './client_node_metadata.js'

export type ClientGraphEncoding = {
  graphType: number
  graphWhich: number
}

export const CLIENT_GRAPH_ENCODING_BY_SUB_TYPE: Record<
  ClientGraphSubType,
  ClientGraphEncoding
> = ${jsonConst(GRAPH_ENCODING_BY_SUB_TYPE)}

export function getClientGraphEncoding(subType: ClientGraphSubType): ClientGraphEncoding {
  return CLIENT_GRAPH_ENCODING_BY_SUB_TYPE[subType]
}
`
  )
}

function emitClientGraphModes(capability: ClientGraphCapability) {
  write(
    'src/definitions/client_graph_modes.ts',
    `${generatedHeader()}import type { ClientGraphSubType } from '../thirdparty/Genshin-Impact-Miliastra-Wonderland-Code-Node-Editor-Pack/node_data/client_node_metadata.js'

export const CLIENT_GRAPH_SUB_TYPES = ${jsonConst(SUB_TYPES)} as const

export const CLIENT_GRAPH_METHOD_BY_SUB_TYPE: Record<ClientGraphSubType, string> = {
  character_skill: 'characterSkill',
  creation_skill: 'creationSkill',
  creation_status: 'creationStatus',
  creation_status_decision: 'creationStatusDecision',
  bool_filter: 'boolFilter',
  int_filter: 'intFilter'
}

export const CLIENT_GRAPH_SUB_TYPE_BY_METHOD = Object.fromEntries(
  Object.entries(CLIENT_GRAPH_METHOD_BY_SUB_TYPE).map(([subType, method]) => [method, subType])
) as Record<string, ClientGraphSubType>

export const CLIENT_GRAPH_CAPABILITY_BY_SUB_TYPE = ${jsonConst(capability)} as const

export const CLIENT_GRAPH_ENTRY_SPEC_BY_SUB_TYPE = {
  character_skill: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  creation_skill: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  creation_status: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  creation_status_decision: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  bool_filter: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'filter', returnType: 'bool' }
  },
  int_filter: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'filter', returnType: 'int' }
  }
} as const
`
  )
}

function emitClientNodeMetadata(metadata: readonly unknown[]) {
  const metadataPath =
    'src/thirdparty/Genshin-Impact-Miliastra-Wonderland-Code-Node-Editor-Pack/node_data/client_node_metadata.ts'
  const metadataBody = fs.readFileSync(metadataPath, 'utf8')
  const marker = 'export const CLIENT_NODE_METADATA: readonly ClientNodeMetadata[] ='
  const markerIndex = metadataBody.indexOf(marker)
  if (markerIndex < 0) {
    throw new Error(`failed to replace CLIENT_NODE_METADATA in ${metadataPath}`)
  }
  const nextMetadataBody = `${metadataBody.slice(
    0,
    markerIndex
  )}${marker} ${jsonConst(metadata)} as const`
  write(metadataPath, nextMetadataBody)
}

function main() {
  const capability = readJson<Partial<ClientGraphCapability>>('resources/client_graph_capability.json')
  const metadata = readJson<readonly unknown[]>('resources/client_node_metadata.json')

  assertCompleteCapability(capability)
  emitClientGraphEncoding()
  emitClientGraphModes(capability as ClientGraphCapability)
  emitClientNodeMetadata(metadata)

  console.log('[ok] generated client nodegraph modules')
}

main()
