import fs from 'node:fs'
import path from 'node:path'

import ts from 'typescript'

import { buildClientEnumBinding, type ClientEnumBinding } from './client_enum_binding.js'
import { generateClientNodes, type FlowMetadataEntry, type MetaRecord } from './client_nodes_codegen.js'
import { buildDocNameAlignment } from './doc_name_alignment.js'

type ClientGraphSubType =
  | 'character_skill'
  | 'creation_skill'
  | 'creation_status'
  | 'creation_status_decision'
  | 'bool_filter'
  | 'int_filter'

type ClientGraphCapability = Record<
  ClientGraphSubType,
  {
    beyond: { status: string; reason: string }
    classic: { status: string; reason: string }
  }
>

const SUB_TYPES: readonly ClientGraphSubType[] = [
  'character_skill',
  'creation_skill',
  'creation_status',
  'creation_status_decision',
  'bool_filter',
  'int_filter'
]

const GRAPH_ENCODING_BY_SUB_TYPE: Record<
  ClientGraphSubType,
  { graphType: number; graphWhich: number }
> = {
  bool_filter: { graphType: 20001, graphWhich: 10 },
  int_filter: { graphType: 20006, graphWhich: 47 },
  character_skill: { graphType: 20002, graphWhich: 11 },
  creation_skill: { graphType: 20008, graphWhich: 52 },
  creation_status_decision: { graphType: 20007, graphWhich: 51 },
  creation_status: { graphType: 20009, graphWhich: 53 }
}

function readJson<T>(file: string): T {
  return JSON.parse(fs.readFileSync(file, 'utf8')) as T
}

function write(file: string, body: string) {
  fs.mkdirSync(path.dirname(file), { recursive: true })
  fs.writeFileSync(file, body.endsWith('\n') ? body : `${body}\n`, 'utf8')
}

function assertCompleteCapability(capability: Partial<ClientGraphCapability>) {
  const missing = SUB_TYPES.filter((subType) => !capability[subType])
  if (missing.length) {
    throw new Error(`client graph capability missing sub types: ${missing.join(', ')}`)
  }
}

function generatedHeader() {
  return '// This file is generated by scripts/client-nodegraph/generate-client-nodegraph-modules.ts.\n'
}

function jsonConst(value: unknown) {
  return JSON.stringify(value, null, 2)
}

function emitClientGraphEncoding() {
  write(
    'src/thirdparty/Genshin-Impact-Miliastra-Wonderland-Code-Node-Editor-Pack/node_data/client_graph_encoding.ts',
    `${generatedHeader()}import type { ClientGraphSubType } from './client_node_metadata.js'

export type ClientGraphEncoding = {
  graphType: number
  graphWhich: number
}

export const CLIENT_GRAPH_ENCODING_BY_SUB_TYPE: Record<
  ClientGraphSubType,
  ClientGraphEncoding
> = ${jsonConst(GRAPH_ENCODING_BY_SUB_TYPE)}

export function getClientGraphEncoding(subType: ClientGraphSubType): ClientGraphEncoding {
  return CLIENT_GRAPH_ENCODING_BY_SUB_TYPE[subType]
}
`
  )
}

function emitClientGraphModes(capability: ClientGraphCapability) {
  write(
    'src/definitions/client_graph_modes.ts',
    `${generatedHeader()}import type { ClientGraphSubType } from '../thirdparty/Genshin-Impact-Miliastra-Wonderland-Code-Node-Editor-Pack/node_data/client_node_metadata.js'

export const CLIENT_GRAPH_SUB_TYPES = ${jsonConst(SUB_TYPES)} as const

export const CLIENT_GRAPH_METHOD_BY_SUB_TYPE: Record<ClientGraphSubType, string> = {
  character_skill: 'characterSkill',
  creation_skill: 'creationSkill',
  creation_status: 'creationStatus',
  creation_status_decision: 'creationStatusDecision',
  bool_filter: 'boolFilter',
  int_filter: 'intFilter'
}

export const CLIENT_GRAPH_SUB_TYPE_BY_METHOD = Object.fromEntries(
  Object.entries(CLIENT_GRAPH_METHOD_BY_SUB_TYPE).map(([subType, method]) => [method, subType])
) as Record<string, ClientGraphSubType>

export const CLIENT_GRAPH_CAPABILITY_BY_SUB_TYPE = ${jsonConst(capability)} as const

export const CLIENT_GRAPH_ENTRY_SPEC_BY_SUB_TYPE = {
  character_skill: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  creation_skill: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  creation_status: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  creation_status_decision: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  bool_filter: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'filter', returnType: 'bool' }
  },
  int_filter: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'filter', returnType: 'int' }
  }
} as const
`
  )
}

// ---------------------------------------------------------------------------
// Scoped helper globals capability (evidence: resources/client_node_metadata.json)
// ---------------------------------------------------------------------------

type ClientGraphMode = 'beyond' | 'classic'

type MetadataRecord = {
  subType: ClientGraphSubType
  nodeType: string
  sampleFile: string
}

type HelperMemberSpec = {
  helper: string
  member?: string
  /** server f method names whose snake_case nodeType must exist as evidence */
  requiredMethods?: string[]
  /** if set, member is needs_developer_confirmation and never implemented */
  confirm?: string
  /** if set, member is a decided gap (developer decision, blocked like timer) */
  blocked?: string
  note?: string
}

type ClientScopedGlobalCapability = {
  helper: string
  member?: string
  subTypes: ClientGraphSubType[]
  modes: ClientGraphMode[]
  backedBy: Array<{
    subType: ClientGraphSubType
    nodeType: string
    methodName: string
    sampleFile: string
  }>
  status: 'supported' | 'partial' | 'needs_developer_confirmation' | 'gap'
  note?: string
}

const HELPER_MEMBER_SPECS: HelperMemberSpec[] = [
  {
    helper: 'send',
    confirm:
      'client signal nodes (向服务器节点图发送信号/通知服务器节点图) are not proven equivalent to server send()'
  },
  {
    helper: 'player',
    blocked: 'client graphs have no node to look up a player entity by id; use self / getSelfEntity instead'
  },
  { helper: 'self', requiredMethods: ['getSelfEntity'] },
  {
    helper: 'stage',
    requiredMethods: ['getStageEntity'],
    note: 'maps to getStageEntity in creation_status families only'
  },
  {
    helper: 'level',
    requiredMethods: ['getStageEntity'],
    note: 'same mapping as stage'
  },
  { helper: 'Mathf', member: 'Abs', requiredMethods: ['absoluteValueOperation'] },
  { helper: 'Mathf', member: 'FloorToInt', requiredMethods: ['roundToIntegerOperation'] },
  { helper: 'Mathf', member: 'CeilToInt', requiredMethods: ['roundToIntegerOperation'] },
  { helper: 'Mathf', member: 'RoundToInt', requiredMethods: ['roundToIntegerOperation'] },
  { helper: 'Mathf', member: 'Sqrt', requiredMethods: ['arithmeticSquareRootOperation'] },
  { helper: 'Mathf', member: 'Pow', requiredMethods: ['exponentiation'] },
  { helper: 'Mathf', member: 'Log', requiredMethods: ['logarithmOperation'] },
  { helper: 'Mathf', member: 'Sin', requiredMethods: ['sineFunction'] },
  { helper: 'Mathf', member: 'Cos', requiredMethods: ['cosineFunction'] },
  { helper: 'Mathf', member: 'Tan', requiredMethods: ['tangentFunction'] },
  {
    helper: 'Random',
    member: 'Range',
    requiredMethods: ['getRandomNumber']
  },
  {
    helper: 'Random',
    member: 'value',
    requiredMethods: ['getRandomNumber']
  },
  ...['zero', 'one', 'up', 'down', 'left', 'right', 'forward', 'back'].map((member) => ({
    helper: 'Vector3',
    member,
    requiredMethods: ['create3dVector'],
    note: 'constant vector built via client create3d_vector node'
  })),
  { helper: 'Vector3', member: 'Dot', requiredMethods: ['_3dVectorDotProduct'] },
  { helper: 'Vector3', member: 'Cross', requiredMethods: ['_3dVectorCrossProduct'] },
  {
    helper: 'Vector3',
    member: 'Distance',
    requiredMethods: ['distanceBetweenTwoCoordinatePoints']
  },
  { helper: 'Vector3', member: 'Angle', requiredMethods: ['_3dVectorAngle'] },
  { helper: 'Vector3', member: 'Normalize', requiredMethods: ['_3dVectorNormalization'] },
  { helper: 'Vector3', member: 'Magnitude', requiredMethods: ['_3dVectorModuloOperation'] },
  { helper: 'Vector3', member: 'Add', requiredMethods: ['_3dVectorAddition'] },
  { helper: 'Vector3', member: 'Sub', requiredMethods: ['_3dVectorSubtraction'] },
  { helper: 'Vector3', member: 'Scale', requiredMethods: ['_3dVectorZoom'] },
  { helper: 'Vector3', member: 'Rotation', requiredMethods: ['_3dVectorRotation'] },
  {
    helper: 'Vector3',
    member: 'Lerp',
    requiredMethods: ['_3dVectorSubtraction', '_3dVectorZoom', '_3dVectorAddition']
  },
  {
    helper: 'Vector3',
    member: 'ClampMagnitude',
    requiredMethods: [
      'initLocalVariable',
      'setLocalVariable',
      'greaterThan',
      'doubleBranch',
      '_3dVectorModuloOperation',
      '_3dVectorNormalization',
      '_3dVectorZoom'
    ]
  },
  { helper: 'GameObject', member: 'Find', requiredMethods: ['queryEntityByGuid'] },
  {
    helper: 'GameObject',
    member: 'FindWithTag',
    requiredMethods: ['getEntityListByUnitTag', 'getCorrespondingValueFromList']
  },
  {
    helper: 'GameObject',
    member: 'FindGameObjectsWithTag',
    requiredMethods: ['getEntityListByUnitTag']
  },
  {
    helper: 'GameObject',
    member: 'FindByPrefabId',
    requiredMethods: ['getEntitiesWithSpecifiedPrefabOnTheField']
  },
  ...['setTimeout', 'setInterval', 'clearTimeout', 'clearInterval'].map((helper) => ({
    helper,
    confirm:
      'no client timer feature proven by resource JSON; server timer globals must not leak into client handlers'
  }))
]

// keep leading underscores: `_3dVectorDotProduct` -> `_3d_vector_dot_product`
function camelToSnake(name: string): string {
  return name.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`)
}

function deriveScopedGlobalsCapability(metadata: MetadataRecord[]): ClientScopedGlobalCapability[] {
  const bySubType = new Map<ClientGraphSubType, Map<string, MetadataRecord>>()
  for (const record of metadata) {
    const map = bySubType.get(record.subType) ?? new Map<string, MetadataRecord>()
    bySubType.set(record.subType, map)
    if (!map.has(record.nodeType)) map.set(record.nodeType, record)
  }

  return HELPER_MEMBER_SPECS.map((spec) => {
    if (spec.confirm || spec.blocked) {
      return {
        helper: spec.helper,
        ...(spec.member ? { member: spec.member } : {}),
        subTypes: [],
        modes: [],
        backedBy: [],
        status: spec.confirm ? ('needs_developer_confirmation' as const) : ('gap' as const),
        note: (spec.confirm ?? spec.blocked)!
      }
    }
    const required = spec.requiredMethods ?? []
    const subTypes: ClientGraphSubType[] = []
    const backedBy: ClientScopedGlobalCapability['backedBy'] = []
    for (const subType of SUB_TYPES) {
      const nodeTypes = bySubType.get(subType)
      if (!nodeTypes) continue
      const records = required.map((method) => nodeTypes.get(camelToSnake(method)))
      if (records.some((r) => !r)) continue
      subTypes.push(subType)
      required.forEach((method, i) => {
        backedBy.push({
          subType,
          nodeType: records[i]!.nodeType,
          methodName: method,
          sampleFile: records[i]!.sampleFile
        })
      })
    }
    const status =
      subTypes.length === 0 ? 'gap' : subTypes.length === SUB_TYPES.length ? 'supported' : 'partial'
    return {
      helper: spec.helper,
      ...(spec.member ? { member: spec.member } : {}),
      subTypes,
      // classic mode capability is still unknown; only beyond is claimed
      modes: subTypes.length ? (['beyond'] as ClientGraphMode[]) : [],
      backedBy,
      status,
      ...(spec.note ? { note: spec.note } : {})
    }
  })
}

function emitClientScopedGlobals(capability: ClientScopedGlobalCapability[]) {
  const membersBySubType: Record<string, Record<string, string[]>> = {}
  for (const subType of SUB_TYPES) membersBySubType[subType] = {}
  for (const entry of capability) {
    if (entry.status !== 'supported' && entry.status !== 'partial') continue
    for (const subType of entry.subTypes) {
      const helpers = membersBySubType[subType]
      const members = (helpers[entry.helper] ??= [])
      if (entry.member) members.push(entry.member)
    }
  }

  write(
    'resources/client_scoped_globals_capability.json',
    JSON.stringify(capability, null, 2)
  )
  write(
    'src/definitions/client_scoped_globals.ts',
    `${generatedHeader()}import type { ClientGraphSubType } from '../thirdparty/Genshin-Impact-Miliastra-Wonderland-Code-Node-Editor-Pack/node_data/client_node_metadata.js'

export type ClientScopedGlobalStatus =
  | 'supported'
  | 'partial'
  | 'needs_developer_confirmation'
  | 'gap'

export type ClientScopedGlobalCapability = {
  helper: string
  member?: string
  subTypes: ClientGraphSubType[]
  modes: ('beyond' | 'classic')[]
  backedBy: Array<{
    subType: ClientGraphSubType
    nodeType: string
    methodName: string
    sampleFile: string
  }>
  status: ClientScopedGlobalStatus
  note?: string
}

export const CLIENT_SCOPED_GLOBALS_CAPABILITY: readonly ClientScopedGlobalCapability[] = ${jsonConst(capability)}

/**
 * helper -> supported member names per sub type (empty array marks a bare
 * helper like \`self\` that is itself supported).
 */
export const CLIENT_SCOPED_GLOBAL_MEMBERS_BY_SUB_TYPE: Record<
  ClientGraphSubType,
  Readonly<Record<string, readonly string[]>>
> = ${jsonConst(membersBySubType)}

/** helper names that must never resolve to server implementations in client handlers */
export const CLIENT_BLOCKED_SERVER_HELPERS = [
  'setTimeout',
  'setInterval',
  'clearTimeout',
  'clearInterval'
] as const
`
  )
}

// ---------------------------------------------------------------------------
// Client method modes and execution flow metadata (Task 15)
// ---------------------------------------------------------------------------

type ServerMethodSignature = {
  methodName: string
  params: string[]
  returnType: string
  typeParams: string[]
  docs: string
}

function extractServerMethodSignatures(): Map<string, ServerMethodSignature> {
  const filePath = 'src/definitions/nodes.ts'
  const source = ts.createSourceFile(
    filePath,
    fs.readFileSync(filePath, 'utf8'),
    ts.ScriptTarget.Latest,
    true
  )
  const result = new Map<string, ServerMethodSignature>()

  const serverClass = source.statements.find(
    (stmt): stmt is ts.ClassDeclaration =>
      ts.isClassDeclaration(stmt) && stmt.name?.text === 'ServerExecutionFlowFunctions'
  )
  if (!serverClass) throw new Error('ServerExecutionFlowFunctions class not found in nodes.ts')

  for (const member of serverClass.members) {
    if (!ts.isMethodDeclaration(member) || !ts.isIdentifier(member.name)) continue
    const methodName = member.name.text
    if (methodName.startsWith('__')) continue
    const jsDocs = ts.getJSDocCommentsAndTags(member)
    const docs = jsDocs
      .map((doc) => doc.getText())
      .join('\n')
      .trim()
    const signature: ServerMethodSignature = {
      methodName,
      params: member.parameters.map((p) => p.getText().replace(/\s+/g, ' ')),
      returnType: member.type ? member.type.getText().replace(/\s+/g, ' ') : 'void',
      typeParams: (member.typeParameters ?? []).map((tp) => tp.getText().replace(/\s+/g, ' ')),
      docs
    }
    // keep the first overload/implementation only
    if (!result.has(methodName)) result.set(methodName, signature)
  }
  return result
}

function emitClientMethodModes(
  flowMetadata: FlowMetadataEntry[],
  methodsBySubType: Record<string, string[]>
) {
  write('resources/client_execution_flow_metadata.json', JSON.stringify(flowMetadata, null, 2))
  write(
    'src/definitions/client_method_modes.ts',
    `${generatedHeader()}export const CLIENT_NODE_METHODS_BY_SUB_TYPE = ${jsonConst(methodsBySubType)} as const

export type ClientNodeMethodBySubType = typeof CLIENT_NODE_METHODS_BY_SUB_TYPE
`
  )
}

/**
 * Cross-check generated client signatures against same-named server methods.
 * Pure report: differences are expected (client pins differ), but every drift
 * should be explainable from metadata/doc evidence.
 */
function deriveServerSignatureDrift(
  flowMetadata: FlowMetadataEntry[],
  signatures: Map<string, ServerMethodSignature>
) {
  const drift: Array<{
    methodName: string
    nodeType: string
    server: { params: string[]; returnType: string }
    client: { params: string[]; returns: string[] | null }
    notes: string[]
  }> = []
  let shared = 0
  for (const entry of flowMetadata) {
    const server = signatures.get(entry.methodName)
    if (!server) continue
    shared += 1
    const clientParams = entry.params.map((p) => `${p.name}: ${p.irType}`)
    const clientReturns = entry.returns?.map((r) => `${r.name}: ${r.irType}`) ?? null
    const notes: string[] = []
    // callbacks (control flow) are part of the server param list; compare counts loosely
    const serverValueParams = server.params.filter((p) => !/=>/.test(p))
    if (serverValueParams.length !== entry.params.length) notes.push('param_count_mismatch')
    const serverVoid = server.returnType === 'void'
    if (serverVoid !== (clientReturns === null)) notes.push('return_shape_mismatch')
    if (!notes.length) continue
    drift.push({
      methodName: entry.methodName,
      nodeType: entry.nodeType,
      server: { params: server.params, returnType: server.returnType },
      client: { params: clientParams, returns: clientReturns },
      notes
    })
  }
  return { shared, drift }
}

// ---------------------------------------------------------------------------
// Client-only enum classes (task 四.1, seeds: resources/client_enum_seed.*.json)
// ---------------------------------------------------------------------------

function emitClientEnums(binding: ClientEnumBinding) {
  const classes = binding.clientOnlyClasses
    .map((cls) => {
      const members = cls.members
        .map(
          (m) => `  /**
   * ${m.name}
   *
   * ${m.zhName}
   */
  static readonly ${m.name} = new enumeration('${cls.className}', '${m.key}') as ${cls.className}`
        )
        .join('\n')
      return `/** ${cls.zhName} */
export class ${cls.className} extends enumeration {
  declare private readonly __brand${cls.className}: '${cls.className}'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

${members}
}`
    })
    .join('\n\n')

  write(
    'src/definitions/client_enums.ts',
    `${generatedHeader()}// Client-only enum classes derived from resources/client_enum_seed.*.json
// (枚举匹配 dropdown census + node param samples). Server-shared classes live
// in ./enum.ts; encoder values for these classes come from client_enum_values.ts.
import { enumeration } from '../runtime/value.js'

export type ClientEnumerationTypeMap = {
${binding.clientOnlyClasses.map((c) => `  ${c.className}: ${c.className}`).join('\n')}
}

${classes}
`
  )
  write(
    'src/thirdparty/Genshin-Impact-Miliastra-Wonderland-Code-Node-Editor-Pack/node_data/client_enum_values.ts',
    `${generatedHeader()}/** enumeration value string -> gia numeric value (client-only enum classes) */
export const CLIENT_ENUM_VALUES: Record<string, number> = ${jsonConst(binding.valueByKey)}
`
  )
}

function emitClientNodeMetadata(
  metadata: readonly unknown[],
  argPinsBySubType: Record<string, Record<string, number[]>>
) {
  // enrich extractor records with the codegen-derived arg->pin mapping so the
  // IR->GIA transform can fill hidden pins while IR args stay signature-ordered
  const enriched = (metadata as Array<{ subType: string; nodeType: string }>).map((record) => {
    const argPins = argPinsBySubType[record.subType]?.[record.nodeType]
    return argPins ? { ...record, argPins } : record
  })
  const metadataPath =
    'src/thirdparty/Genshin-Impact-Miliastra-Wonderland-Code-Node-Editor-Pack/node_data/client_node_metadata.ts'
  const metadataBody = fs.readFileSync(metadataPath, 'utf8')
  const marker = 'export const CLIENT_NODE_METADATA: readonly ClientNodeMetadata[] ='
  const markerIndex = metadataBody.indexOf(marker)
  if (markerIndex < 0) {
    throw new Error(`failed to replace CLIENT_NODE_METADATA in ${metadataPath}`)
  }
  const nextMetadataBody = `${metadataBody.slice(
    0,
    markerIndex
  )}${marker} ${jsonConst(enriched)} as const`
  write(metadataPath, nextMetadataBody)
}

function main() {
  const capability = readJson<Partial<ClientGraphCapability>>('resources/client_graph_capability.json')
  const metadata = readJson<readonly unknown[]>('resources/client_node_metadata.json')

  assertCompleteCapability(capability)
  emitClientGraphEncoding()
  emitClientGraphModes(capability as ClientGraphCapability)
  emitClientScopedGlobals(deriveScopedGlobalsCapability(metadata as MetadataRecord[]))

  const alignment = buildDocNameAlignment()
  const enumBinding = buildClientEnumBinding()
  emitClientEnums(enumBinding)
  const generated = generateClientNodes(metadata as MetaRecord[], alignment, enumBinding)
  emitClientNodeMetadata(metadata, generated.argPinsBySubType)
  write('src/definitions/client_nodes.ts', generated.classFileBody)
  emitClientMethodModes(generated.flowMetadata, generated.methodsBySubType)
  write('tests/client_generated/_generation_gaps.json', JSON.stringify(generated.gaps, null, 2))

  const { shared, drift } = deriveServerSignatureDrift(
    generated.flowMetadata,
    extractServerMethodSignatures()
  )
  write('tests/client_generated/_server_drift.json', JSON.stringify({ shared, drift }, null, 2))

  const methodCount = Object.values(generated.methodsBySubType).reduce((n, m) => n + m.length, 0)
  console.log(
    `[ok] generated client nodegraph modules (${methodCount} methods, ` +
      `${generated.gaps.length} gaps, ${drift.length}/${shared} drifted shared methods)`
  )
}

main()
