// This file is generated by scripts/client-nodegraph/generate-client-nodegraph-modules.ts.
// Client-only enum classes derived from resources/client_enum_seed.*.json
// (枚举匹配 dropdown census + node param samples). Server-shared classes live
// in ./enum.ts; encoder values for these classes come from client_enum_values.ts.

import { enumeration } from '../runtime/value.js'

export type ClientEnumerationTypeMap = {
  AttackLayerConfig: AttackLayerConfig
  FilterReturnType: FilterReturnType
  HitLevel: HitLevel
  KnockbackDirectionType: KnockbackDirectionType
  PreAimingEndReason: PreAimingEndReason
  RetracingType: RetracingType
  RotationDirection: RotationDirection
  RotationType: RotationType
  ScanStatus: ScanStatus
  SectorDetectionDirection: SectorDetectionDirection
  TacticSpeed: TacticSpeed
  TacticType: TacticType
  TargetEntity: TargetEntity
  TargetSortingRules: TargetSortingRules
}

/** 攻击盒层级配置 */
export class AttackLayerConfig extends enumeration {
  declare private readonly __brandAttackLayerConfig: 'AttackLayerConfig'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * OnlyOnHitHurtbox
   *
   * 只命中受击盒
   */
  static readonly OnlyOnHitHurtbox = new enumeration(
    'AttackLayerConfig',
    'attack_layer_config_only_on_hit_hurtbox'
  ) as AttackLayerConfig
  /**
   * OnlyOnHitScene
   *
   * 只命中场景
   */
  static readonly OnlyOnHitScene = new enumeration(
    'AttackLayerConfig',
    'attack_layer_config_only_on_hit_scene'
  ) as AttackLayerConfig
  /**
   * HitAll
   *
   * 全部命中
   */
  static readonly HitAll = new enumeration(
    'AttackLayerConfig',
    'attack_layer_config_hit_all'
  ) as AttackLayerConfig
}

/** 筛选器返回类型 */
export class FilterReturnType extends enumeration {
  declare private readonly __brandFilterReturnType: 'FilterReturnType'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * ReturnBoolean
   *
   * 返回布尔型
   */
  static readonly ReturnBoolean = new enumeration(
    'FilterReturnType',
    'filter_return_type_return_boolean'
  ) as FilterReturnType
  /**
   * ReturnInteger
   *
   * 返回整型
   */
  static readonly ReturnInteger = new enumeration(
    'FilterReturnType',
    'filter_return_type_return_integer'
  ) as FilterReturnType
}

/** 受击等级 */
export class HitLevel extends enumeration {
  declare private readonly __brandHitLevel: 'HitLevel'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * NoEffect
   *
   * 无效果
   */
  static readonly NoEffect = new enumeration('HitLevel', 'hit_level_no_effect') as HitLevel
  /**
   * LightTremor
   *
   * 轻颤
   */
  static readonly LightTremor = new enumeration('HitLevel', 'hit_level_light_tremor') as HitLevel
  /**
   * LightHit
   *
   * 轻受击
   */
  static readonly LightHit = new enumeration('HitLevel', 'hit_level_light_hit') as HitLevel
  /**
   * KnockbackHit
   *
   * 击退受击
   */
  static readonly KnockbackHit = new enumeration('HitLevel', 'hit_level_knockback_hit') as HitLevel
  /**
   * Launch
   *
   * 挑飞
   */
  static readonly Launch = new enumeration('HitLevel', 'hit_level_launch') as HitLevel
}

/** 击退方向类型 */
export class KnockbackDirectionType extends enumeration {
  declare private readonly __brandKnockbackDirectionType: 'KnockbackDirectionType'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * LineConnectingAttackerAndHitPoint
   *
   * 攻击者与受击点的连线
   */
  static readonly LineConnectingAttackerAndHitPoint = new enumeration(
    'KnockbackDirectionType',
    'knockback_direction_type_line_connecting_attacker_and_hit_point'
  ) as KnockbackDirectionType
  /**
   * HitboxOnHitDirection
   *
   * 攻击盒命中方向
   */
  static readonly HitboxOnHitDirection = new enumeration(
    'KnockbackDirectionType',
    'knockback_direction_type_hitbox_on_hit_direction'
  ) as KnockbackDirectionType
  /**
   * LineConnectingAttackersOwnerAndHitPoint
   *
   * 攻击者主人与受击点连线
   */
  static readonly LineConnectingAttackersOwnerAndHitPoint = new enumeration(
    'KnockbackDirectionType',
    'knockback_direction_type_line_connecting_attackers_owner_and_hit_point'
  ) as KnockbackDirectionType
  /**
   * TangentLineBetweenAttackerAndHitPoint
   *
   * 攻击者与受击点连线切线
   */
  static readonly TangentLineBetweenAttackerAndHitPoint = new enumeration(
    'KnockbackDirectionType',
    'knockback_direction_type_tangent_line_between_attacker_and_hit_point'
  ) as KnockbackDirectionType
  /**
   * OppositeDirectionToHit
   *
   * 受击反方向
   */
  static readonly OppositeDirectionToHit = new enumeration(
    'KnockbackDirectionType',
    'knockback_direction_type_opposite_direction_to_hit'
  ) as KnockbackDirectionType
  /**
   * AttackersFacingOrientation
   *
   * 攻击者面朝朝向
   */
  static readonly AttackersFacingOrientation = new enumeration(
    'KnockbackDirectionType',
    'knockback_direction_type_attackers_facing_orientation'
  ) as KnockbackDirectionType
  /**
   * OppositeDirectionToLineConnectingAttackerAndHitPoint
   *
   * 攻击者与受击点连线反方向
   */
  static readonly OppositeDirectionToLineConnectingAttackerAndHitPoint = new enumeration(
    'KnockbackDirectionType',
    'knockback_direction_type_opposite_direction_to_line_connecting_attacker_and_hit_point'
  ) as KnockbackDirectionType
}

/** 预瞄准结束原因 */
export class PreAimingEndReason extends enumeration {
  declare private readonly __brandPreAimingEndReason: 'PreAimingEndReason'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * None
   *
   * 无
   */
  static readonly None = new enumeration(
    'PreAimingEndReason',
    'pre_aiming_end_reason_none'
  ) as PreAimingEndReason
  /**
   * Completed
   *
   * 完成
   */
  static readonly Completed = new enumeration(
    'PreAimingEndReason',
    'pre_aiming_end_reason_completed'
  ) as PreAimingEndReason
  /**
   * Cancelled
   *
   * 取消
   */
  static readonly Cancelled = new enumeration(
    'PreAimingEndReason',
    'pre_aiming_end_reason_cancelled'
  ) as PreAimingEndReason
}

/** 溯源类型 */
export class RetracingType extends enumeration {
  declare private readonly __brandRetracingType: 'RetracingType'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * Self
   *
   * 自身
   */
  static readonly Self = new enumeration('RetracingType', 'retracing_type_self') as RetracingType
  /**
   * SelfOwner
   *
   * 自身所有者
   */
  static readonly SelfOwner = new enumeration(
    'RetracingType',
    'retracing_type_self_owner'
  ) as RetracingType
  /**
   * TopLayerSelfOwner
   *
   * 自身最上层所有者
   */
  static readonly TopLayerSelfOwner = new enumeration(
    'RetracingType',
    'retracing_type_top_layer_self_owner'
  ) as RetracingType
}

/** 旋转方向 */
export class RotationDirection extends enumeration {
  declare private readonly __brandRotationDirection: 'RotationDirection'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * Default
   *
   * 默认
   */
  static readonly Default = new enumeration(
    'RotationDirection',
    'rotation_direction_default'
  ) as RotationDirection
  /**
   * Clockwise
   *
   * 顺时针
   */
  static readonly Clockwise = new enumeration(
    'RotationDirection',
    'rotation_direction_clockwise'
  ) as RotationDirection
  /**
   * Counterclockwise
   *
   * 逆时针
   */
  static readonly Counterclockwise = new enumeration(
    'RotationDirection',
    'rotation_direction_counterclockwise'
  ) as RotationDirection
}

/** 转向模式 */
export class RotationType extends enumeration {
  declare private readonly __brandRotationType: 'RotationType'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * TargetFirstThenInput
   *
   * 先目标后输入
   */
  static readonly TargetFirstThenInput = new enumeration(
    'RotationType',
    'rotation_type_target_first_then_input'
  ) as RotationType
  /**
   * InputOrientation
   *
   * 输入朝向
   */
  static readonly InputOrientation = new enumeration(
    'RotationType',
    'rotation_type_input_orientation'
  ) as RotationType
  /**
   * TargetOrientation
   *
   * 目标朝向
   */
  static readonly TargetOrientation = new enumeration(
    'RotationType',
    'rotation_type_target_orientation'
  ) as RotationType
  /**
   * TargetFirstThenCamera
   *
   * 先目标后镜头
   */
  static readonly TargetFirstThenCamera = new enumeration(
    'RotationType',
    'rotation_type_target_first_then_camera'
  ) as RotationType
  /**
   * CameraOrientation
   *
   * 镜头朝向
   */
  static readonly CameraOrientation = new enumeration(
    'RotationType',
    'rotation_type_camera_orientation'
  ) as RotationType
  /**
   * InputFirstThenTarget
   *
   * 先输入后目标
   */
  static readonly InputFirstThenTarget = new enumeration(
    'RotationType',
    'rotation_type_input_first_then_target'
  ) as RotationType
}

/** 扫描状态 */
export class ScanStatus extends enumeration {
  declare private readonly __brandScanStatus: 'ScanStatus'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * UnusableTarget
   *
   * 目标不可用
   */
  static readonly UnusableTarget = new enumeration(
    'ScanStatus',
    'scan_status_unusable_target'
  ) as ScanStatus
  /**
   * CurrentScanTarget
   *
   * 当前扫描目标
   */
  static readonly CurrentScanTarget = new enumeration(
    'ScanStatus',
    'scan_status_current_scan_target'
  ) as ScanStatus
  /**
   * CandidateTarget
   *
   * 候选目标
   */
  static readonly CandidateTarget = new enumeration(
    'ScanStatus',
    'scan_status_candidate_target'
  ) as ScanStatus
  /**
   * ConditionNotMet
   *
   * 不满足条件
   */
  static readonly ConditionNotMet = new enumeration(
    'ScanStatus',
    'scan_status_condition_not_met'
  ) as ScanStatus
}

/** 扇形检测方向 */
export class SectorDetectionDirection extends enumeration {
  declare private readonly __brandSectorDetectionDirection: 'SectorDetectionDirection'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * FromInsideOut
   *
   * 由内向外
   */
  static readonly FromInsideOut = new enumeration(
    'SectorDetectionDirection',
    'sector_detection_direction_from_inside_out'
  ) as SectorDetectionDirection
  /**
   * Clockwise
   *
   * 顺时针
   */
  static readonly Clockwise = new enumeration(
    'SectorDetectionDirection',
    'sector_detection_direction_clockwise'
  ) as SectorDetectionDirection
  /**
   * Counterclockwise
   *
   * 逆时针
   */
  static readonly Counterclockwise = new enumeration(
    'SectorDetectionDirection',
    'sector_detection_direction_counterclockwise'
  ) as SectorDetectionDirection
}

/** 战术速度 */
export class TacticSpeed extends enumeration {
  declare private readonly __brandTacticSpeed: 'TacticSpeed'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * Walk
   *
   * 走
   */
  static readonly Walk = new enumeration('TacticSpeed', 'tactic_speed_walk') as TacticSpeed
  /**
   * Run
   *
   * 跑
   */
  static readonly Run = new enumeration('TacticSpeed', 'tactic_speed_run') as TacticSpeed
}

/** 战术类型 */
export class TacticType extends enumeration {
  declare private readonly __brandTacticType: 'TacticType'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * None
   *
   * 无
   */
  static readonly None = new enumeration('TacticType', 'tactic_type_none') as TacticType
  /**
   * StayMotionless
   *
   * 战术：静止不动
   */
  static readonly StayMotionless = new enumeration(
    'TacticType',
    'tactic_type_stay_motionless'
  ) as TacticType
  /**
   * MoveToTheTargetPosition
   *
   * 战术：移动到目标点
   */
  static readonly MoveToTheTargetPosition = new enumeration(
    'TacticType',
    'tactic_type_move_to_the_target_position'
  ) as TacticType
  /**
   * MoveToTheTargetEntity
   *
   * 战术：移动到目标实体
   */
  static readonly MoveToTheTargetEntity = new enumeration(
    'TacticType',
    'tactic_type_move_to_the_target_entity'
  ) as TacticType
  /**
   * RotateToTheSpecifiedDirection
   *
   * 战术：旋转到指定朝向
   */
  static readonly RotateToTheSpecifiedDirection = new enumeration(
    'TacticType',
    'tactic_type_rotate_to_the_specified_direction'
  ) as TacticType
  /**
   * RotateBySpecifiedAngle
   *
   * 战术：旋转指定角度
   */
  static readonly RotateBySpecifiedAngle = new enumeration(
    'TacticType',
    'tactic_type_rotate_by_specified_angle'
  ) as TacticType
  /**
   * GroundPursuit
   *
   * 战术：地面追击
   */
  static readonly GroundPursuit = new enumeration(
    'TacticType',
    'tactic_type_ground_pursuit'
  ) as TacticType
  /**
   * GroundEscape
   *
   * 战术：地面逃跑
   */
  static readonly GroundEscape = new enumeration(
    'TacticType',
    'tactic_type_ground_escape'
  ) as TacticType
  /**
   * GroundIdleRoaming
   *
   * 战术：地面闲逛
   */
  static readonly GroundIdleRoaming = new enumeration(
    'TacticType',
    'tactic_type_ground_idle_roaming'
  ) as TacticType
  /**
   * ReturnToSpawnPointAfterLeavingBattle
   *
   * 战术：脱战后返回出生点
   */
  static readonly ReturnToSpawnPointAfterLeavingBattle = new enumeration(
    'TacticType',
    'tactic_type_return_to_spawn_point_after_leaving_battle'
  ) as TacticType
  /**
   * GroundStandoff
   *
   * 战术：地面对峙
   */
  static readonly GroundStandoff = new enumeration(
    'TacticType',
    'tactic_type_ground_standoff'
  ) as TacticType
  /**
   * ExecutePatrol
   *
   * 战术：执行巡逻
   */
  static readonly ExecutePatrol = new enumeration(
    'TacticType',
    'tactic_type_execute_patrol'
  ) as TacticType
  /**
   * RotateTowardsTargetEntity
   *
   * 战术：旋转朝向目标实体
   */
  static readonly RotateTowardsTargetEntity = new enumeration(
    'TacticType',
    'tactic_type_rotate_towards_target_entity'
  ) as TacticType
}

/** 目标实体 */
export class TargetEntity extends enumeration {
  declare private readonly __brandTargetEntity: 'TargetEntity'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * AggroTarget
   *
   * 仇恨目标
   */
  static readonly AggroTarget = new enumeration(
    'TargetEntity',
    'target_entity_aggro_target'
  ) as TargetEntity
  /**
   * Self
   *
   * 自己
   */
  static readonly Self = new enumeration('TargetEntity', 'target_entity_self') as TargetEntity
  /**
   * StageEntity
   *
   * 关卡实体
   */
  static readonly StageEntity = new enumeration(
    'TargetEntity',
    'target_entity_stage_entity'
  ) as TargetEntity
}

/** 筛选规则 */
export class TargetSortingRules extends enumeration {
  declare private readonly __brandTargetSortingRules: 'TargetSortingRules'
  private constructor() {
    super('')
    // 防止用户通过字符串传参构造枚举导致的意外行为
    throw new Error('you should not create an enum instance')
  }

  /**
   * DefaultSorting
   *
   * 默认排序
   */
  static readonly DefaultSorting = new enumeration(
    'TargetSortingRules',
    'target_sorting_rules_default_sorting'
  ) as TargetSortingRules
  /**
   * RandomOrder
   *
   * 随机排序
   */
  static readonly RandomOrder = new enumeration(
    'TargetSortingRules',
    'target_sorting_rules_random_order'
  ) as TargetSortingRules
  /**
   * SortFromNearToFar
   *
   * 从近到远排序
   */
  static readonly SortFromNearToFar = new enumeration(
    'TargetSortingRules',
    'target_sorting_rules_sort_from_near_to_far'
  ) as TargetSortingRules
}
