// This file is generated by scripts/client-nodegraph/generate-client-nodegraph-modules.ts.

import type { ClientGraphSubType } from '../thirdparty/Genshin-Impact-Miliastra-Wonderland-Code-Node-Editor-Pack/node_data/client_node_metadata.js'

export const CLIENT_GRAPH_SUB_TYPES = [
  'character_skill',
  'character_control_skill',
  'creation_skill',
  'creation_status',
  'creation_status_decision',
  'bool_filter',
  'int_filter'
] as const

export const CLIENT_GRAPH_METHOD_BY_SUB_TYPE: Record<ClientGraphSubType, string> = {
  character_skill: 'characterSkill',
  character_control_skill: 'characterControlSkill',
  creation_skill: 'creationSkill',
  creation_status: 'creationStatus',
  creation_status_decision: 'creationStatusDecision',
  bool_filter: 'boolFilter',
  int_filter: 'intFilter'
}

export const CLIENT_GRAPH_SUB_TYPE_BY_METHOD = Object.fromEntries(
  Object.entries(CLIENT_GRAPH_METHOD_BY_SUB_TYPE).map(([subType, method]) => [method, subType])
) as Record<string, ClientGraphSubType>

export const CLIENT_GSTS_FUNCTION_PREFIXES_BY_SUB_TYPE = {
  character_skill: ['gstsClientCharacterSkill', 'gstsCharacterSkill'],
  character_control_skill: ['gstsClientCharacterControlSkill', 'gstsCharacterControlSkill'],
  creation_skill: ['gstsClientCreationSkill', 'gstsCreationSkill'],
  creation_status: ['gstsClientCreationStatus', 'gstsCreationStatus'],
  creation_status_decision: ['gstsClientCreationStatusDecision', 'gstsCreationStatusDecision'],
  bool_filter: ['gstsClientBoolFilter', 'gstsBoolFilter'],
  int_filter: ['gstsClientIntFilter', 'gstsIntFilter']
} as const satisfies Record<ClientGraphSubType, readonly [string, string]>

export const CLIENT_GSTS_FUNCTION_PREFIX_ENTRIES = Object.entries(
  CLIENT_GSTS_FUNCTION_PREFIXES_BY_SUB_TYPE
)
  .flatMap(([subType, prefixes]) =>
    prefixes.map((prefix) => ({ prefix, subType: subType as ClientGraphSubType }))
  )
  .sort((a, b) => b.prefix.length - a.prefix.length)

export const CLIENT_GSTS_FUNCTION_PREFIXES = CLIENT_GSTS_FUNCTION_PREFIX_ENTRIES.map(
  (entry) => entry.prefix
)

export function getClientGraphSubTypeForGstsFunctionName(
  name: string | undefined
): ClientGraphSubType | undefined {
  if (!name) return undefined
  return CLIENT_GSTS_FUNCTION_PREFIX_ENTRIES.find((entry) => name.startsWith(entry.prefix))?.subType
}

export const CLIENT_F_GLOBAL_NAME_BY_SUB_TYPE = {
  character_skill: 'fCharacterSkill',
  character_control_skill: 'fCharacterControlSkill',
  creation_skill: 'fCreationSkill',
  creation_status: 'fCreationStatus',
  creation_status_decision: 'fCreationStatusDecision',
  bool_filter: 'fBoolFilter',
  int_filter: 'fIntFilter'
} as const satisfies Record<ClientGraphSubType, string>

export const CLIENT_GRAPH_SUB_TYPE_BY_F_GLOBAL_NAME = Object.fromEntries(
  Object.entries(CLIENT_F_GLOBAL_NAME_BY_SUB_TYPE).map(([subType, name]) => [name, subType])
) as Record<string, ClientGraphSubType>

export const CLIENT_GRAPH_CAPABILITY_BY_SUB_TYPE = {
  bool_filter: {
    beyond: {
      status: 'available',
      reason: ''
    },
    classic: {
      status: 'unknown',
      reason: 'client classic mode requires sample confirmation'
    }
  },
  character_control_skill: {
    beyond: {
      status: 'available',
      reason: ''
    },
    classic: {
      status: 'unknown',
      reason: 'client classic mode requires sample confirmation'
    }
  },
  character_skill: {
    beyond: {
      status: 'available',
      reason: ''
    },
    classic: {
      status: 'unknown',
      reason: 'client classic mode requires sample confirmation'
    }
  },
  creation_skill: {
    beyond: {
      status: 'available',
      reason: ''
    },
    classic: {
      status: 'unknown',
      reason: 'client classic mode requires sample confirmation'
    }
  },
  creation_status: {
    beyond: {
      status: 'available',
      reason: ''
    },
    classic: {
      status: 'unknown',
      reason: 'client classic mode requires sample confirmation'
    }
  },
  creation_status_decision: {
    beyond: {
      status: 'available',
      reason: ''
    },
    classic: {
      status: 'unknown',
      reason: 'client classic mode requires sample confirmation'
    }
  },
  int_filter: {
    beyond: {
      status: 'available',
      reason: ''
    },
    classic: {
      status: 'unknown',
      reason: 'client classic mode requires sample confirmation'
    }
  }
} as const

export const CLIENT_GRAPH_ENTRY_SPEC_BY_SUB_TYPE = {
  character_skill: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  character_control_skill: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  creation_skill: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  creation_status: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  creation_status_decision: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'start', returnType: 'void' }
  },
  bool_filter: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'filter', returnType: 'bool' }
  },
  int_filter: {
    event: 'start',
    startNodeType: 'node_graph_begins',
    handler: { params: [], shape: 'filter', returnType: 'int' }
  }
} as const
