// This file is generated by scripts/client-nodegraph/generate-client-nodegraph-modules.ts.

import type { ClientGraphMode, ClientGraphSubType } from '../runtime/IR.js'
import type { RuntimeReturnValueTypeMap } from '../runtime/value.js'
import type { ClientEntityHelperMethods } from './client_nodes.js'
import type { EntityBase, EntityHelperAll } from './entity_helpers.js'

export type ClientEntityHelperBinding = {
  kind: 'method' | 'getter'
  methodName: string
  insertIndex: number | null
}

export const CLIENT_ENTITY_HELPER_BINDINGS_BY_SUB_TYPE_AND_MODE = {
  character_skill: {
    beyond: {
      addUnitStatus: {
        kind: 'method',
        methodName: 'addUnitStatus',
        insertIndex: 0
      },
      aggroList: {
        kind: 'method',
        methodName: 'getTheAggroListOfTheSpecifiedEntity',
        insertIndex: 0
      },
      aggroTarget: {
        kind: 'method',
        methodName: 'getTheAggroTargetOfTheSpecifiedEntity',
        insertIndex: 0
      },
      checkThePresetStatusValueOfTheComplexCreation: {
        kind: 'method',
        methodName: 'checkThePresetStatusValueOfTheComplexCreation',
        insertIndex: 0
      },
      clearTheAggroListOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'clearTheAggroListOfTheSpecifiedEntity',
        insertIndex: 0
      },
      faction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      fixedPointProjectileLaunch: {
        kind: 'method',
        methodName: 'fixedPointProjectileLaunch',
        insertIndex: 3
      },
      get: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getAllEntitiesWithinTheCollisionTrigger: {
        kind: 'method',
        methodName: 'getAllEntitiesWithinTheCollisionTrigger',
        insertIndex: 0
      },
      getCharacterEntityOfSpecifiedPlayer: {
        kind: 'method',
        methodName: 'getCharacterEntityOfSpecifiedPlayer',
        insertIndex: 0
      },
      getCustomVariable: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getEntityLocation: {
        kind: 'method',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      getEntityRotation: {
        kind: 'method',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      getEntitySCurrentActiveScanTags: {
        kind: 'method',
        methodName: 'getEntitySCurrentActiveScanTags',
        insertIndex: 0
      },
      getEntitySScanStatus: {
        kind: 'method',
        methodName: 'getEntitySScanStatus',
        insertIndex: 0
      },
      getEntitySType: {
        kind: 'method',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      getEntitySUnitTagList: {
        kind: 'method',
        methodName: 'getEntitySUnitTagList',
        insertIndex: 0
      },
      getPlayerEntityToWhichTheCharacterBelongs: {
        kind: 'method',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      getPreset: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getPresetStatus: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getRayDetectionResult: {
        kind: 'method',
        methodName: 'getRayDetectionResult',
        insertIndex: 0
      },
      getTargetAttachmentPointLocation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointLocation',
        insertIndex: 0
      },
      getTargetAttachmentPointRotation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointRotation',
        insertIndex: 0
      },
      getTheAggroListOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'getTheAggroListOfTheSpecifiedEntity',
        insertIndex: 0
      },
      getTheAggroTargetOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'getTheAggroTargetOfTheSpecifiedEntity',
        insertIndex: 0
      },
      getUnitAttackTarget: {
        kind: 'method',
        methodName: 'getUnitAttackTarget',
        insertIndex: 0
      },
      guid: {
        kind: 'getter',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      increaseTheAggroValueOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'increaseTheAggroValueOfTheSpecifiedEntity',
        insertIndex: 0
      },
      inputDevice: {
        kind: 'getter',
        methodName: 'getPlayerClientInputDeviceType',
        insertIndex: null
      },
      isInCombat: {
        kind: 'method',
        methodName: 'queryIfSpecifiedEntityIsInCombat',
        insertIndex: 0
      },
      isOnField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      player: {
        kind: 'getter',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      pos: {
        kind: 'getter',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      queryEntityFaction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      queryGuidByEntity: {
        kind: 'method',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      queryIfEntityIsOnTheField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      queryIfSpecifiedEntityIsInCombat: {
        kind: 'method',
        methodName: 'queryIfSpecifiedEntityIsInCombat',
        insertIndex: 0
      },
      queryWhetherPlayerIsCurrentlyInVoiceChat: {
        kind: 'method',
        methodName: 'queryWhetherPlayerIsCurrentlyInVoiceChat',
        insertIndex: 0
      },
      recoverCharacterSHp: {
        kind: 'method',
        methodName: 'recoverCharacterSHp',
        insertIndex: 0
      },
      removeTargetEntityFromAggroList: {
        kind: 'method',
        methodName: 'removeTargetEntityFromAggroList',
        insertIndex: 0
      },
      removeUnitStatus: {
        kind: 'method',
        methodName: 'removeUnitStatus',
        insertIndex: 0
      },
      rotation: {
        kind: 'getter',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      setAggroValue: {
        kind: 'method',
        methodName: 'setTheAggroValueOfSpecifiedEntity',
        insertIndex: 0
      },
      setOwnAttackTarget: {
        kind: 'method',
        methodName: 'setOwnAttackTarget',
        insertIndex: 0
      },
      setTheAggroValueOfSpecifiedEntity: {
        kind: 'method',
        methodName: 'setTheAggroValueOfSpecifiedEntity',
        insertIndex: 0
      },
      setTheAggroValueOfTheSpecifiedEntityProportionally: {
        kind: 'method',
        methodName: 'setTheAggroValueOfTheSpecifiedEntityProportionally',
        insertIndex: 0
      },
      tauntTarget: {
        kind: 'method',
        methodName: 'tauntTarget',
        insertIndex: 0
      },
      transferTheAggroValueOfTheSpecifiedEntityProportionally: {
        kind: 'method',
        methodName: 'transferTheAggroValueOfTheSpecifiedEntityProportionally',
        insertIndex: 0
      },
      type: {
        kind: 'getter',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      unitTags: {
        kind: 'method',
        methodName: 'getEntitySUnitTagList',
        insertIndex: 0
      },
      whetherTheEntityHasTheSpecifiedUnitStatus: {
        kind: 'method',
        methodName: 'whetherTheEntityHasTheSpecifiedUnitStatus',
        insertIndex: 0
      }
    },
    classic: {}
  },
  character_control_skill: {
    beyond: {
      addTemporaryAcceleration: {
        kind: 'method',
        methodName: 'addTemporaryAcceleration',
        insertIndex: 0
      },
      addTemporaryMovementParameterValues: {
        kind: 'method',
        methodName: 'addTemporaryMovementParameterValues',
        insertIndex: 0
      },
      addUnitStatus: {
        kind: 'method',
        methodName: 'addUnitStatus',
        insertIndex: 0
      },
      addVelocity: {
        kind: 'method',
        methodName: 'addVelocity',
        insertIndex: 0
      },
      aggroList: {
        kind: 'method',
        methodName: 'getTheAggroListOfTheSpecifiedEntity',
        insertIndex: 0
      },
      aggroTarget: {
        kind: 'method',
        methodName: 'getTheAggroTargetOfTheSpecifiedEntity',
        insertIndex: 0
      },
      checkThePresetStatusValueOfTheComplexCreation: {
        kind: 'method',
        methodName: 'checkThePresetStatusValueOfTheComplexCreation',
        insertIndex: 0
      },
      clearTheAggroListOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'clearTheAggroListOfTheSpecifiedEntity',
        insertIndex: 0
      },
      faction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      fixedPointProjectileLaunch: {
        kind: 'method',
        methodName: 'fixedPointProjectileLaunch',
        insertIndex: 3
      },
      forward: {
        kind: 'getter',
        methodName: 'getControlMotorForwardDirection',
        insertIndex: 0
      },
      get: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getAllEntitiesWithinTheCollisionTrigger: {
        kind: 'method',
        methodName: 'getAllEntitiesWithinTheCollisionTrigger',
        insertIndex: 0
      },
      getCharacterEntityOfSpecifiedPlayer: {
        kind: 'method',
        methodName: 'getCharacterEntityOfSpecifiedPlayer',
        insertIndex: 0
      },
      getControlMotorCurrentVelocity: {
        kind: 'method',
        methodName: 'getControlMotorCurrentVelocity',
        insertIndex: 0
      },
      getControlMotorForwardDirection: {
        kind: 'method',
        methodName: 'getControlMotorForwardDirection',
        insertIndex: 0
      },
      getControlMotorMovementParameters: {
        kind: 'method',
        methodName: 'getControlMotorMovementParameters',
        insertIndex: 0
      },
      getControlMotorTargetTurningDirection: {
        kind: 'method',
        methodName: 'getControlMotorTargetTurningDirection',
        insertIndex: 0
      },
      getCustomVariable: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getEntityLocation: {
        kind: 'method',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      getEntityRotation: {
        kind: 'method',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      getEntitySCurrentActiveScanTags: {
        kind: 'method',
        methodName: 'getEntitySCurrentActiveScanTags',
        insertIndex: 0
      },
      getEntitySScanStatus: {
        kind: 'method',
        methodName: 'getEntitySScanStatus',
        insertIndex: 0
      },
      getEntitySType: {
        kind: 'method',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      getEntitySUnitTagList: {
        kind: 'method',
        methodName: 'getEntitySUnitTagList',
        insertIndex: 0
      },
      getPlayerEntityToWhichTheCharacterBelongs: {
        kind: 'method',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      getPreset: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getPresetStatus: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getRayDetectionResult: {
        kind: 'method',
        methodName: 'getRayDetectionResult',
        insertIndex: 0
      },
      getTargetAttachmentPointLocation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointLocation',
        insertIndex: 0
      },
      getTargetAttachmentPointRotation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointRotation',
        insertIndex: 0
      },
      getTheAggroListOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'getTheAggroListOfTheSpecifiedEntity',
        insertIndex: 0
      },
      getTheAggroTargetOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'getTheAggroTargetOfTheSpecifiedEntity',
        insertIndex: 0
      },
      getUnitAttackTarget: {
        kind: 'method',
        methodName: 'getUnitAttackTarget',
        insertIndex: 0
      },
      getWhetherControlMotorIsGrounded: {
        kind: 'method',
        methodName: 'getWhetherControlMotorIsGrounded',
        insertIndex: 0
      },
      guid: {
        kind: 'getter',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      increaseTheAggroValueOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'increaseTheAggroValueOfTheSpecifiedEntity',
        insertIndex: 0
      },
      inputDevice: {
        kind: 'getter',
        methodName: 'getPlayerClientInputDeviceType',
        insertIndex: null
      },
      isInCombat: {
        kind: 'method',
        methodName: 'queryIfSpecifiedEntityIsInCombat',
        insertIndex: 0
      },
      isOnField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      player: {
        kind: 'getter',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      pos: {
        kind: 'getter',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      queryEntityFaction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      queryGuidByEntity: {
        kind: 'method',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      queryIfEntityIsOnTheField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      queryIfSpecifiedEntityIsInCombat: {
        kind: 'method',
        methodName: 'queryIfSpecifiedEntityIsInCombat',
        insertIndex: 0
      },
      queryWhetherPlayerIsCurrentlyInVoiceChat: {
        kind: 'method',
        methodName: 'queryWhetherPlayerIsCurrentlyInVoiceChat',
        insertIndex: 0
      },
      recoverCharacterSHp: {
        kind: 'method',
        methodName: 'recoverCharacterSHp',
        insertIndex: 0
      },
      removeTargetEntityFromAggroList: {
        kind: 'method',
        methodName: 'removeTargetEntityFromAggroList',
        insertIndex: 0
      },
      removeUnitStatus: {
        kind: 'method',
        methodName: 'removeUnitStatus',
        insertIndex: 0
      },
      rotation: {
        kind: 'getter',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      setAggroValue: {
        kind: 'method',
        methodName: 'setTheAggroValueOfSpecifiedEntity',
        insertIndex: 0
      },
      setControlMotorToUngroundedState: {
        kind: 'method',
        methodName: 'setControlMotorToUngroundedState',
        insertIndex: 0
      },
      setOwnAttackTarget: {
        kind: 'method',
        methodName: 'setOwnAttackTarget',
        insertIndex: 0
      },
      setTheAggroValueOfSpecifiedEntity: {
        kind: 'method',
        methodName: 'setTheAggroValueOfSpecifiedEntity',
        insertIndex: 0
      },
      setTheAggroValueOfTheSpecifiedEntityProportionally: {
        kind: 'method',
        methodName: 'setTheAggroValueOfTheSpecifiedEntityProportionally',
        insertIndex: 0
      },
      tauntTarget: {
        kind: 'method',
        methodName: 'tauntTarget',
        insertIndex: 0
      },
      transferTheAggroValueOfTheSpecifiedEntityProportionally: {
        kind: 'method',
        methodName: 'transferTheAggroValueOfTheSpecifiedEntityProportionally',
        insertIndex: 0
      },
      type: {
        kind: 'getter',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      unitTags: {
        kind: 'method',
        methodName: 'getEntitySUnitTagList',
        insertIndex: 0
      },
      whetherTheEntityHasTheSpecifiedUnitStatus: {
        kind: 'method',
        methodName: 'whetherTheEntityHasTheSpecifiedUnitStatus',
        insertIndex: 0
      }
    },
    classic: {}
  },
  creation_skill: {
    beyond: {
      addUnitStatus: {
        kind: 'method',
        methodName: 'addUnitStatus',
        insertIndex: 0
      },
      aggroList: {
        kind: 'method',
        methodName: 'getTheAggroListOfTheSpecifiedEntity',
        insertIndex: 0
      },
      aggroTarget: {
        kind: 'method',
        methodName: 'getTheAggroTargetOfTheSpecifiedEntity',
        insertIndex: 0
      },
      checkThePresetStatusValueOfTheComplexCreation: {
        kind: 'method',
        methodName: 'checkThePresetStatusValueOfTheComplexCreation',
        insertIndex: 0
      },
      clearTheAggroListOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'clearTheAggroListOfTheSpecifiedEntity',
        insertIndex: 0
      },
      currentTarget: {
        kind: 'getter',
        methodName: 'getCreationSCurrentTarget',
        insertIndex: 0
      },
      faction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      fixedPointProjectileLaunch: {
        kind: 'method',
        methodName: 'fixedPointProjectileLaunch',
        insertIndex: 3
      },
      get: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getAllEntitiesWithinTheCollisionTrigger: {
        kind: 'method',
        methodName: 'getAllEntitiesWithinTheCollisionTrigger',
        insertIndex: 0
      },
      getCreationSCurrentTarget: {
        kind: 'method',
        methodName: 'getCreationSCurrentTarget',
        insertIndex: 0
      },
      getCustomVariable: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getEntityLocation: {
        kind: 'method',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      getEntityRotation: {
        kind: 'method',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      getEntitySType: {
        kind: 'method',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      getEntitySUnitTagList: {
        kind: 'method',
        methodName: 'getEntitySUnitTagList',
        insertIndex: 0
      },
      getPlayerEntityToWhichTheCharacterBelongs: {
        kind: 'method',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      getPreset: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getPresetStatus: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getRayDetectionResult: {
        kind: 'method',
        methodName: 'getRayDetectionResult',
        insertIndex: 0
      },
      getSubEntityList: {
        kind: 'method',
        methodName: 'getSubEntityList',
        insertIndex: 0
      },
      getTargetAttachmentPointLocation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointLocation',
        insertIndex: 0
      },
      getTargetAttachmentPointRotation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointRotation',
        insertIndex: 0
      },
      getTheAggroListOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'getTheAggroListOfTheSpecifiedEntity',
        insertIndex: 0
      },
      getTheAggroTargetOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'getTheAggroTargetOfTheSpecifiedEntity',
        insertIndex: 0
      },
      getUnitAttackTarget: {
        kind: 'method',
        methodName: 'getUnitAttackTarget',
        insertIndex: 0
      },
      guid: {
        kind: 'getter',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      increaseTheAggroValueOfTheSpecifiedEntity: {
        kind: 'method',
        methodName: 'increaseTheAggroValueOfTheSpecifiedEntity',
        insertIndex: 0
      },
      isInCombat: {
        kind: 'method',
        methodName: 'queryIfSpecifiedEntityIsInCombat',
        insertIndex: 0
      },
      isOnField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      player: {
        kind: 'getter',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      pos: {
        kind: 'getter',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      queryEntityFaction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      queryGuidByEntity: {
        kind: 'method',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      queryIfEntityIsOnTheField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      queryIfSpecifiedEntityIsInCombat: {
        kind: 'method',
        methodName: 'queryIfSpecifiedEntityIsInCombat',
        insertIndex: 0
      },
      recoverCreationSHp: {
        kind: 'method',
        methodName: 'recoverCreationSHp',
        insertIndex: 0
      },
      removeTargetEntityFromAggroList: {
        kind: 'method',
        methodName: 'removeTargetEntityFromAggroList',
        insertIndex: 0
      },
      removeUnitStatus: {
        kind: 'method',
        methodName: 'removeUnitStatus',
        insertIndex: 0
      },
      rotation: {
        kind: 'getter',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      setAggroValue: {
        kind: 'method',
        methodName: 'setTheAggroValueOfSpecifiedEntity',
        insertIndex: 0
      },
      setTheAggroValueOfSpecifiedEntity: {
        kind: 'method',
        methodName: 'setTheAggroValueOfSpecifiedEntity',
        insertIndex: 0
      },
      setTheAggroValueOfTheSpecifiedEntityProportionally: {
        kind: 'method',
        methodName: 'setTheAggroValueOfTheSpecifiedEntityProportionally',
        insertIndex: 0
      },
      tauntTarget: {
        kind: 'method',
        methodName: 'tauntTarget',
        insertIndex: 0
      },
      transferTheAggroValueOfTheSpecifiedEntityProportionally: {
        kind: 'method',
        methodName: 'transferTheAggroValueOfTheSpecifiedEntityProportionally',
        insertIndex: 0
      },
      type: {
        kind: 'getter',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      unitTags: {
        kind: 'method',
        methodName: 'getEntitySUnitTagList',
        insertIndex: 0
      },
      whetherTheEntityHasTheSpecifiedUnitStatus: {
        kind: 'method',
        methodName: 'whetherTheEntityHasTheSpecifiedUnitStatus',
        insertIndex: 0
      }
    },
    classic: {
      activeCharacter: {
        kind: 'getter',
        methodName: 'getActiveCharacterOfSpecifiedPlayer',
        insertIndex: 0
      },
      addUnitStatus: {
        kind: 'method',
        methodName: 'addUnitStatus',
        insertIndex: 0
      },
      characters: {
        kind: 'getter',
        methodName: 'getPlayerSCharacterList',
        insertIndex: 0
      },
      checkClassicModeCharacterId: {
        kind: 'method',
        methodName: 'checkClassicModeCharacterId',
        insertIndex: 0
      },
      checkThePresetStatusValueOfTheComplexCreation: {
        kind: 'method',
        methodName: 'checkThePresetStatusValueOfTheComplexCreation',
        insertIndex: 0
      },
      classicModeId: {
        kind: 'getter',
        methodName: 'checkClassicModeCharacterId',
        insertIndex: 0
      },
      currentTarget: {
        kind: 'getter',
        methodName: 'getCreationSCurrentTarget',
        insertIndex: 0
      },
      faction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      fixedPointProjectileLaunch: {
        kind: 'method',
        methodName: 'fixedPointProjectileLaunch',
        insertIndex: 3
      },
      get: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getActiveCharacterOfSpecifiedPlayer: {
        kind: 'method',
        methodName: 'getActiveCharacterOfSpecifiedPlayer',
        insertIndex: 0
      },
      getAllEntitiesWithinTheCollisionTrigger: {
        kind: 'method',
        methodName: 'getAllEntitiesWithinTheCollisionTrigger',
        insertIndex: 0
      },
      getCreationSCurrentTarget: {
        kind: 'method',
        methodName: 'getCreationSCurrentTarget',
        insertIndex: 0
      },
      getCustomVariable: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getEntityLocation: {
        kind: 'method',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      getEntityRotation: {
        kind: 'method',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      getEntitySType: {
        kind: 'method',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      getEntitySUnitTagList: {
        kind: 'method',
        methodName: 'getEntitySUnitTagList',
        insertIndex: 0
      },
      getPlayerEntityToWhichTheCharacterBelongs: {
        kind: 'method',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      getPlayerSCharacterList: {
        kind: 'method',
        methodName: 'getPlayerSCharacterList',
        insertIndex: 0
      },
      getPreset: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getPresetStatus: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getRayDetectionResult: {
        kind: 'method',
        methodName: 'getRayDetectionResult',
        insertIndex: 0
      },
      getSubEntityList: {
        kind: 'method',
        methodName: 'getSubEntityList',
        insertIndex: 0
      },
      getTargetAttachmentPointLocation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointLocation',
        insertIndex: 0
      },
      getTargetAttachmentPointRotation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointRotation',
        insertIndex: 0
      },
      getUnitAttackTarget: {
        kind: 'method',
        methodName: 'getUnitAttackTarget',
        insertIndex: 0
      },
      guid: {
        kind: 'getter',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      isOnField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      player: {
        kind: 'getter',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      pos: {
        kind: 'getter',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      queryEntityFaction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      queryGuidByEntity: {
        kind: 'method',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      queryIfEntityIsOnTheField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      recoverCreationSHp: {
        kind: 'method',
        methodName: 'recoverCreationSHp',
        insertIndex: 0
      },
      removeUnitStatus: {
        kind: 'method',
        methodName: 'removeUnitStatus',
        insertIndex: 0
      },
      rotation: {
        kind: 'getter',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      type: {
        kind: 'getter',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      unitTags: {
        kind: 'method',
        methodName: 'getEntitySUnitTagList',
        insertIndex: 0
      },
      whetherTheEntityHasTheSpecifiedUnitStatus: {
        kind: 'method',
        methodName: 'whetherTheEntityHasTheSpecifiedUnitStatus',
        insertIndex: 0
      }
    }
  },
  creation_status: {
    beyond: {
      tacticMoveToTheTargetEntity: {
        kind: 'method',
        methodName: 'tacticMoveToTheTargetEntity',
        insertIndex: 1
      },
      tacticRotateToTheTargetEntity: {
        kind: 'method',
        methodName: 'tacticRotateToTheTargetEntity',
        insertIndex: 1
      }
    },
    classic: {
      tacticMoveToTheTargetEntity: {
        kind: 'method',
        methodName: 'tacticMoveToTheTargetEntity',
        insertIndex: 1
      },
      tacticRotateToTheTargetEntity: {
        kind: 'method',
        methodName: 'tacticRotateToTheTargetEntity',
        insertIndex: 1
      }
    }
  },
  creation_status_decision: {
    beyond: {},
    classic: {}
  },
  bool_filter: {
    beyond: {
      checkThePresetStatusValueOfTheComplexCreation: {
        kind: 'method',
        methodName: 'checkThePresetStatusValueOfTheComplexCreation',
        insertIndex: 0
      },
      faction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      get: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getAllEntitiesWithinTheCollisionTrigger: {
        kind: 'method',
        methodName: 'getAllEntitiesWithinTheCollisionTrigger',
        insertIndex: 0
      },
      getCharacterEntityOfSpecifiedPlayer: {
        kind: 'method',
        methodName: 'getCharacterEntityOfSpecifiedPlayer',
        insertIndex: 0
      },
      getCustomVariable: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getEntityLocation: {
        kind: 'method',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      getEntityRotation: {
        kind: 'method',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      getEntitySCurrentActiveScanTags: {
        kind: 'method',
        methodName: 'getEntitySCurrentActiveScanTags',
        insertIndex: 0
      },
      getEntitySScanStatus: {
        kind: 'method',
        methodName: 'getEntitySScanStatus',
        insertIndex: 0
      },
      getEntitySType: {
        kind: 'method',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      getPlayerEntityToWhichTheCharacterBelongs: {
        kind: 'method',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      getPreset: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getPresetStatus: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getRayDetectionResult: {
        kind: 'method',
        methodName: 'getRayDetectionResult',
        insertIndex: 0
      },
      getTargetAttachmentPointLocation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointLocation',
        insertIndex: 0
      },
      getTargetAttachmentPointRotation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointRotation',
        insertIndex: 0
      },
      getUnitAttackTarget: {
        kind: 'method',
        methodName: 'getUnitAttackTarget',
        insertIndex: 0
      },
      guid: {
        kind: 'getter',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      inputDevice: {
        kind: 'getter',
        methodName: 'getPlayerClientInputDeviceType',
        insertIndex: null
      },
      isOnField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      player: {
        kind: 'getter',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      pos: {
        kind: 'getter',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      queryEntityFaction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      queryGuidByEntity: {
        kind: 'method',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      queryIfEntityIsOnTheField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      queryWhetherPlayerIsCurrentlyInVoiceChat: {
        kind: 'method',
        methodName: 'queryWhetherPlayerIsCurrentlyInVoiceChat',
        insertIndex: 0
      },
      rotation: {
        kind: 'getter',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      type: {
        kind: 'getter',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      whetherTheEntityHasTheSpecifiedUnitStatus: {
        kind: 'method',
        methodName: 'whetherTheEntityHasTheSpecifiedUnitStatus',
        insertIndex: 0
      }
    },
    classic: {
      activeCharacter: {
        kind: 'getter',
        methodName: 'getActiveCharacterOfSpecifiedPlayer',
        insertIndex: 0
      },
      characters: {
        kind: 'getter',
        methodName: 'getPlayerSCharacterList',
        insertIndex: 0
      },
      checkClassicModeCharacterId: {
        kind: 'method',
        methodName: 'checkClassicModeCharacterId',
        insertIndex: 0
      },
      checkThePresetStatusValueOfTheComplexCreation: {
        kind: 'method',
        methodName: 'checkThePresetStatusValueOfTheComplexCreation',
        insertIndex: 0
      },
      classicModeId: {
        kind: 'getter',
        methodName: 'checkClassicModeCharacterId',
        insertIndex: 0
      },
      faction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      get: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getActiveCharacterOfSpecifiedPlayer: {
        kind: 'method',
        methodName: 'getActiveCharacterOfSpecifiedPlayer',
        insertIndex: 0
      },
      getAllEntitiesWithinTheCollisionTrigger: {
        kind: 'method',
        methodName: 'getAllEntitiesWithinTheCollisionTrigger',
        insertIndex: 0
      },
      getCustomVariable: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getEntityLocation: {
        kind: 'method',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      getEntityRotation: {
        kind: 'method',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      getEntitySType: {
        kind: 'method',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      getPlayerEntityToWhichTheCharacterBelongs: {
        kind: 'method',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      getPlayerSCharacterList: {
        kind: 'method',
        methodName: 'getPlayerSCharacterList',
        insertIndex: 0
      },
      getPreset: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getPresetStatus: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getRayDetectionResult: {
        kind: 'method',
        methodName: 'getRayDetectionResult',
        insertIndex: 0
      },
      getTargetAttachmentPointLocation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointLocation',
        insertIndex: 0
      },
      getTargetAttachmentPointRotation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointRotation',
        insertIndex: 0
      },
      getUnitAttackTarget: {
        kind: 'method',
        methodName: 'getUnitAttackTarget',
        insertIndex: 0
      },
      guid: {
        kind: 'getter',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      inputDevice: {
        kind: 'getter',
        methodName: 'getPlayerClientInputDeviceType',
        insertIndex: null
      },
      isOnField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      player: {
        kind: 'getter',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      pos: {
        kind: 'getter',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      queryEntityFaction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      queryGuidByEntity: {
        kind: 'method',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      queryIfEntityIsOnTheField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      queryWhetherPlayerIsCurrentlyInVoiceChat: {
        kind: 'method',
        methodName: 'queryWhetherPlayerIsCurrentlyInVoiceChat',
        insertIndex: 0
      },
      rotation: {
        kind: 'getter',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      type: {
        kind: 'getter',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      whetherTheEntityHasTheSpecifiedUnitStatus: {
        kind: 'method',
        methodName: 'whetherTheEntityHasTheSpecifiedUnitStatus',
        insertIndex: 0
      }
    }
  },
  int_filter: {
    beyond: {
      checkThePresetStatusValueOfTheComplexCreation: {
        kind: 'method',
        methodName: 'checkThePresetStatusValueOfTheComplexCreation',
        insertIndex: 0
      },
      faction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      get: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getAllEntitiesWithinTheCollisionTrigger: {
        kind: 'method',
        methodName: 'getAllEntitiesWithinTheCollisionTrigger',
        insertIndex: 0
      },
      getCharacterEntityOfSpecifiedPlayer: {
        kind: 'method',
        methodName: 'getCharacterEntityOfSpecifiedPlayer',
        insertIndex: 0
      },
      getCustomVariable: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getEntityLocation: {
        kind: 'method',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      getEntityRotation: {
        kind: 'method',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      getEntitySCurrentActiveScanTags: {
        kind: 'method',
        methodName: 'getEntitySCurrentActiveScanTags',
        insertIndex: 0
      },
      getEntitySScanStatus: {
        kind: 'method',
        methodName: 'getEntitySScanStatus',
        insertIndex: 0
      },
      getEntitySType: {
        kind: 'method',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      getPlayerEntityToWhichTheCharacterBelongs: {
        kind: 'method',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      getPreset: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getPresetStatus: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getRayDetectionResult: {
        kind: 'method',
        methodName: 'getRayDetectionResult',
        insertIndex: 0
      },
      getTargetAttachmentPointLocation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointLocation',
        insertIndex: 0
      },
      getTargetAttachmentPointRotation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointRotation',
        insertIndex: 0
      },
      getUnitAttackTarget: {
        kind: 'method',
        methodName: 'getUnitAttackTarget',
        insertIndex: 0
      },
      guid: {
        kind: 'getter',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      inputDevice: {
        kind: 'getter',
        methodName: 'getPlayerClientInputDeviceType',
        insertIndex: null
      },
      isOnField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      player: {
        kind: 'getter',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      pos: {
        kind: 'getter',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      queryEntityFaction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      queryGuidByEntity: {
        kind: 'method',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      queryIfEntityIsOnTheField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      queryWhetherPlayerIsCurrentlyInVoiceChat: {
        kind: 'method',
        methodName: 'queryWhetherPlayerIsCurrentlyInVoiceChat',
        insertIndex: 0
      },
      rotation: {
        kind: 'getter',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      type: {
        kind: 'getter',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      whetherTheEntityHasTheSpecifiedUnitStatus: {
        kind: 'method',
        methodName: 'whetherTheEntityHasTheSpecifiedUnitStatus',
        insertIndex: 0
      }
    },
    classic: {
      activeCharacter: {
        kind: 'getter',
        methodName: 'getActiveCharacterOfSpecifiedPlayer',
        insertIndex: 0
      },
      characters: {
        kind: 'getter',
        methodName: 'getPlayerSCharacterList',
        insertIndex: 0
      },
      checkClassicModeCharacterId: {
        kind: 'method',
        methodName: 'checkClassicModeCharacterId',
        insertIndex: 0
      },
      checkThePresetStatusValueOfTheComplexCreation: {
        kind: 'method',
        methodName: 'checkThePresetStatusValueOfTheComplexCreation',
        insertIndex: 0
      },
      classicModeId: {
        kind: 'getter',
        methodName: 'checkClassicModeCharacterId',
        insertIndex: 0
      },
      faction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      get: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getActiveCharacterOfSpecifiedPlayer: {
        kind: 'method',
        methodName: 'getActiveCharacterOfSpecifiedPlayer',
        insertIndex: 0
      },
      getAllEntitiesWithinTheCollisionTrigger: {
        kind: 'method',
        methodName: 'getAllEntitiesWithinTheCollisionTrigger',
        insertIndex: 0
      },
      getCustomVariable: {
        kind: 'method',
        methodName: 'getCustomVariable',
        insertIndex: 0
      },
      getEntityLocation: {
        kind: 'method',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      getEntityRotation: {
        kind: 'method',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      getEntitySType: {
        kind: 'method',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      getPlayerEntityToWhichTheCharacterBelongs: {
        kind: 'method',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      getPlayerSCharacterList: {
        kind: 'method',
        methodName: 'getPlayerSCharacterList',
        insertIndex: 0
      },
      getPreset: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getPresetStatus: {
        kind: 'method',
        methodName: 'getPresetStatus',
        insertIndex: 0
      },
      getRayDetectionResult: {
        kind: 'method',
        methodName: 'getRayDetectionResult',
        insertIndex: 0
      },
      getTargetAttachmentPointLocation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointLocation',
        insertIndex: 0
      },
      getTargetAttachmentPointRotation: {
        kind: 'method',
        methodName: 'getTargetAttachmentPointRotation',
        insertIndex: 0
      },
      getUnitAttackTarget: {
        kind: 'method',
        methodName: 'getUnitAttackTarget',
        insertIndex: 0
      },
      guid: {
        kind: 'getter',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      inputDevice: {
        kind: 'getter',
        methodName: 'getPlayerClientInputDeviceType',
        insertIndex: null
      },
      isOnField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      player: {
        kind: 'getter',
        methodName: 'getPlayerEntityToWhichTheCharacterBelongs',
        insertIndex: 0
      },
      pos: {
        kind: 'getter',
        methodName: 'getEntityLocation',
        insertIndex: 0
      },
      queryEntityFaction: {
        kind: 'method',
        methodName: 'queryEntityFaction',
        insertIndex: 0
      },
      queryGuidByEntity: {
        kind: 'method',
        methodName: 'queryGuidByEntity',
        insertIndex: 0
      },
      queryIfEntityIsOnTheField: {
        kind: 'method',
        methodName: 'queryIfEntityIsOnTheField',
        insertIndex: 0
      },
      queryWhetherPlayerIsCurrentlyInVoiceChat: {
        kind: 'method',
        methodName: 'queryWhetherPlayerIsCurrentlyInVoiceChat',
        insertIndex: 0
      },
      rotation: {
        kind: 'getter',
        methodName: 'getEntityRotation',
        insertIndex: 0
      },
      type: {
        kind: 'getter',
        methodName: 'getEntitySType',
        insertIndex: 0
      },
      whetherTheEntityHasTheSpecifiedUnitStatus: {
        kind: 'method',
        methodName: 'whetherTheEntityHasTheSpecifiedUnitStatus',
        insertIndex: 0
      }
    }
  }
} as const

export const CLIENT_ENTITY_HELPER_METHOD_NAMES = [
  'addTemporaryAcceleration',
  'addTemporaryMovementParameterValues',
  'addUnitStatus',
  'addVelocity',
  'checkClassicModeCharacterId',
  'checkThePresetStatusValueOfTheComplexCreation',
  'clearTheAggroListOfTheSpecifiedEntity',
  'fixedPointProjectileLaunch',
  'getActiveCharacterOfSpecifiedPlayer',
  'getAllEntitiesWithinTheCollisionTrigger',
  'getCharacterEntityOfSpecifiedPlayer',
  'getControlMotorCurrentVelocity',
  'getControlMotorForwardDirection',
  'getControlMotorMovementParameters',
  'getControlMotorTargetTurningDirection',
  'getCreationSCurrentTarget',
  'getCustomVariable',
  'getEntityLocation',
  'getEntityRotation',
  'getEntitySCurrentActiveScanTags',
  'getEntitySScanStatus',
  'getEntitySType',
  'getEntitySUnitTagList',
  'getPlayerEntityToWhichTheCharacterBelongs',
  'getPlayerSCharacterList',
  'getPresetStatus',
  'getRayDetectionResult',
  'getSubEntityList',
  'getTargetAttachmentPointLocation',
  'getTargetAttachmentPointRotation',
  'getTheAggroListOfTheSpecifiedEntity',
  'getTheAggroTargetOfTheSpecifiedEntity',
  'getUnitAttackTarget',
  'getWhetherControlMotorIsGrounded',
  'increaseTheAggroValueOfTheSpecifiedEntity',
  'queryEntityFaction',
  'queryGuidByEntity',
  'queryIfEntityIsOnTheField',
  'queryIfSpecifiedEntityIsInCombat',
  'queryWhetherPlayerIsCurrentlyInVoiceChat',
  'recoverCharacterSHp',
  'recoverCreationSHp',
  'removeTargetEntityFromAggroList',
  'removeUnitStatus',
  'setControlMotorToUngroundedState',
  'setOwnAttackTarget',
  'setTheAggroValueOfSpecifiedEntity',
  'setTheAggroValueOfTheSpecifiedEntityProportionally',
  'tacticMoveToTheTargetEntity',
  'tacticRotateToTheTargetEntity',
  'tauntTarget',
  'transferTheAggroValueOfTheSpecifiedEntityProportionally',
  'whetherTheEntityHasTheSpecifiedUnitStatus'
] as const

type ClientEntityHelperSurface<T extends ClientGraphSubType, Mode extends ClientGraphMode> = Omit<
  EntityHelperAll,
  keyof ClientEntityHelperMethods<T, Mode>
> &
  ClientEntityHelperMethods<T, Mode>

type ClientEntityHelperName<
  T extends ClientGraphSubType,
  Mode extends ClientGraphMode
> = T extends ClientGraphSubType
  ? Mode extends ClientGraphMode
    ? keyof (typeof CLIENT_ENTITY_HELPER_BINDINGS_BY_SUB_TYPE_AND_MODE)[T][Mode]
    : never
  : never

export type clientEntity<
  T extends ClientGraphSubType = ClientGraphSubType,
  Mode extends ClientGraphMode = ClientGraphMode
> = EntityBase &
  Pick<
    ClientEntityHelperSurface<T, Mode>,
    Extract<ClientEntityHelperName<T, Mode>, keyof ClientEntityHelperSurface<T, Mode>>
  >

export type ClientEntity<
  T extends ClientGraphSubType = ClientGraphSubType,
  Mode extends ClientGraphMode = ClientGraphMode
> = clientEntity<T, Mode>

/** @deprecated Use clientEntity<T, Mode>. */
export type ClientEntityFor<
  T extends ClientGraphSubType,
  Mode extends ClientGraphMode
> = clientEntity<T, Mode>

export type ClientRuntimeReturnValueTypeMap<
  T extends ClientGraphSubType,
  Mode extends ClientGraphMode
> = Omit<RuntimeReturnValueTypeMap, 'entity' | 'entity_list'> & {
  entity: clientEntity<T, Mode>
  entity_list: clientEntity<T, Mode>[]
}
