// This file is generated by scripts/server-nodegraph/generate-server-node-metadata.ts.
// Sources: resources/server_node_static_metadata.json, src/definitions/nodes.ts, and vendor pin records.

/** Public server method arguments whose editor input pins cannot be connected. */
export const SERVER_LITERAL_ARGUMENT_INDEXES_BY_METHOD = {
  setPlayerSCursorClickSelectableTargets: [1]
} as const

/** IR argument indexes keyed by server node type; consumed before physical pin remapping. */
export const SERVER_LITERAL_ARGUMENT_INDEXES_BY_NODE_TYPE = {
  set_player_s_cursor_click_selectable_targets: [1]
} as const
